version: "3.8"
services:
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
      - ./conf:/etc/mysql/conf.d
      - persistent:/var/lib/mysql
    networks:
      - mynetwork

  php:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./..:/var/www/html/
      - ./conf/php.ini:/usr/local/etc/php/php.ini
      - ./conf/apache2.conf:/etc/apache2/apache2.conf
      - ./conf/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./logs/error.log:/usr/local/apache2/logs/error.log
      - ./logs/access.log:/usr/local/apache2/logs/access.log
    networks:
      - mynetwork

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8081:80
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
      UPLOAD_LIMIT: 300M
    depends_on:
      - mysql
    networks:
      - mynetwork

volumes:
  persistent:

networks:
  mynetwork: